version: '3.7'
services:
  py-be:
    build: python
    ports:
      - "8000:8000"
    volumes:
      - ./python:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: ${PY_SERVER:-uvicorn api:app --host 0.0.0.0 --reload}
    restart: ${DOCKER_RESTART:-no}
