version: '3.7'
services:
  py-be:
    build: python
    ports:
      - "8000:8000"
    volumes:
      - ./python:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: ${PY_SERVER:-uvicorn api:app --host 0.0.0.0 --reload}
    restart: ${DOCKER_RESTART:-no}

  java-be:
    build: java
    ports:
      - "8001:8080"
    volumes:
      - ./java:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: ${JAVA_SERVER:-mvn spring-boot:run}
    restart: ${DOCKER_RESTART:-no}
